### ISSUE TITLE
Adjust Padding in What We Do Sections

### ISSUE THREAD

**Issue by h-w-koenig** [Dezudio/dezudio-website#17] opened 2021-08-10 20:01 UTC
2440: 

1. WHAT WE DO / OUR APPROACH titles should NOT have padding-bottom (currently at 0.5rem). 
2. "Platforms that inform..." text box should have margin-bottom of 2.5rem.

We don't think the scroll magic pin spacer min height is going to serve us well. We would consider removing that and just using padding below the "Platforms that inform...." text box to create the space between those two text boxes. @ashleyinpgh is happy to jump on and show you what we're talking about.

1920:

1.  WHAT WE DO / OUR APPROACH titles should have line height of 32px (currently 25px).
2. "Platforms that inform..." text box should have margin-bottom of 2.5rem.

**Comment by raelynno** [comment] 2021-09-26 20:09
Duplicate of #32

**Closed** 2021-09-26 20:09 UTC
