### ISSUE TITLE
Fix Project Caption Boxes

### ISSUE THREAD

**Issue by h-w-koenig** [Dezudio/dezudio-website#18] opened 2021-08-10 20:13 UTC
2440:

1. Adjust padding on all four sides of the caption block to 1.5rem
2. Increase padding-bottom on orange text "Dezudio + University..." to 0.75rem to increase space before white text "MyDecision and MyVoice...". 
3. Adjust line height of orange text to 24/28 (not 24/22).
4. Adjust white text "MyDecision and MyVoice..." to Benton Sans Condensed Light.

These adjustments should apply to all the caption boxes, both dark and light backgrounds.

1920:

1. Adjust padding on all four sides of the caption block to 1rem
2. Increase padding-bottom on orange text "Dezudio + University..." to 0.5rem to increase space before white text "MyDecision and MyVoice...". 
3. Adjust size and line height of orange text to 20/26px.
4. Adjust white text "MyDecision and MyVoice..." to Benton Sans Condensed Light and change type size and line height to 24/32px.

These adjustments should apply to all the caption boxes, both dark and light backgrounds.

**Comment by raelynno** [comment] 2021-09-26 20:08
Duplicate of #32

**Closed by raelynno** 2021-09-26 20:08 UTC
